#!/usr/bin/env python3
"""Validate staging incident ticket drill evidence artifacts."""

from __future__ import annotations

import argparse
import ipaddress
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate incident ticket drill evidence for non-test readiness",
    )
    parser.add_argument(
        "--report-path",
        required=True,
        help="Path to incident_ticket_drill_report.json",
    )
    parser.add_argument(
        "--max-age-hours",
        type=int,
        default=48,
        help="Maximum accepted evidence age in hours",
    )
    parser.add_argument(
        "--require-delivery",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Require successful webhook delivery",
    )
    parser.add_argument(
        "--require-non-test-target",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Require webhook target to be a non-test HTTPS endpoint",
    )
    parser.add_argument(
        "--require-response-links",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Require runbook and escalation roster links to be present",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Optional output JSON path for gate results",
    )
    return parser.parse_args()


def _parse_iso8601(raw: str) -> datetime | None:
    value = str(raw or "").strip()
    if not value:
        return None
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(value)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def _is_non_test_webhook_target(raw_url: str) -> bool:
    parsed = urlsplit(str(raw_url or "").strip())
    if parsed.scheme.lower() != "https":
        return False

    hostname = (parsed.hostname or "").strip().lower()
    if not hostname:
        return False
    if hostname in {"localhost"} or hostname.endswith(".localhost") or hostname.endswith(".local"):
        return False
    if hostname.endswith(".test") or hostname.endswith(".example") or hostname.endswith(".invalid"):
        return False

    try:
        host_ip = ipaddress.ip_address(hostname)
    except ValueError:
        return True

    return not any(
        (
            host_ip.is_private,
            host_ip.is_loopback,
            host_ip.is_link_local,
            host_ip.is_reserved,
            host_ip.is_unspecified,
            host_ip.is_multicast,
        )
    )


def _validate_report(report: dict[str, Any], args: argparse.Namespace) -> dict[str, Any]:
    failures: list[str] = []
    checks: list[dict[str, Any]] = []

    def _record(name: str, passed: bool, message: str) -> None:
        checks.append({"name": name, "passed": passed, "message": message})
        if not passed:
            failures.append(f"{name}: {message}")

    _record(
        "report_passed",
        bool(report.get("passed")),
        (
            "drill report indicates passed=true"
            if report.get("passed")
            else "drill report passed=false"
        ),
    )

    delivery = dict(report.get("delivery", {}) or {})
    _record(
        "delivery_attempted",
        bool(delivery.get("attempted")),
        (
            "webhook delivery was attempted"
            if delivery.get("attempted")
            else "webhook delivery was not attempted"
        ),
    )
    if args.require_delivery:
        _record(
            "delivery_succeeded",
            bool(delivery.get("succeeded")),
            (
                "webhook delivery succeeded"
                if delivery.get("succeeded")
                else "webhook delivery did not succeed"
            ),
        )

    dead_letters = dict(report.get("dead_letters", {}) or {})
    _record(
        "no_dead_letters",
        int(dead_letters.get("queued", 0) or 0) == 0,
        (
            "no dead-letter backlog generated by drill"
            if int(dead_letters.get("queued", 0) or 0) == 0
            else f"dead-letter backlog present: queued={dead_letters.get('queued')}"
        ),
    )

    ticketing = dict(report.get("ticketing", {}) or {})
    _record(
        "ticket_created",
        int(ticketing.get("created", 0) or 0) >= 1,
        (
            "incident ticket creation recorded"
            if int(ticketing.get("created", 0) or 0) >= 1
            else "no incident ticket was created"
        ),
    )

    report_time = _parse_iso8601(str(report.get("timestamp", "")))
    if report_time is None:
        _record("timestamp_parsed", False, "invalid or missing report timestamp")
    else:
        age_hours = max(
            0.0,
            (datetime.now(timezone.utc) - report_time).total_seconds() / 3600.0,
        )
        max_age = max(1, int(args.max_age_hours))
        _record(
            "timestamp_fresh",
            age_hours <= float(max_age),
            (
                f"evidence age {age_hours:.2f}h within max_age_hours={max_age}"
                if age_hours <= float(max_age)
                else f"evidence too old: age={age_hours:.2f}h > max_age_hours={max_age}"
            ),
        )

    webhook = dict(report.get("webhook", {}) or {})
    webhook_url = str(webhook.get("url", "") or "").strip()
    if args.require_non_test_target:
        _record(
            "non_test_target",
            _is_non_test_webhook_target(webhook_url),
            (
                "webhook target is a non-test HTTPS endpoint"
                if _is_non_test_webhook_target(webhook_url)
                else f"webhook target looks test/internal: {webhook_url!r}"
            ),
        )

    response_links = dict(report.get("response_links", {}) or {})
    runbook_url = str(response_links.get("runbook_url", "") or "").strip()
    escalation_roster_url = str(response_links.get("escalation_roster_url", "") or "").strip()
    if args.require_response_links:
        _record(
            "runbook_link_present",
            bool(runbook_url),
            (
                "runbook URL is present in report"
                if runbook_url
                else "runbook URL missing from report.response_links"
            ),
        )
        _record(
            "escalation_roster_link_present",
            bool(escalation_roster_url),
            (
                "escalation roster URL is present in report"
                if escalation_roster_url
                else "escalation roster URL missing from report.response_links"
            ),
        )

    return {
        "passed": len(failures) == 0,
        "failures": failures,
        "checks": checks,
        "report_path": str(args.report_path),
    }


def main() -> int:
    args = _parse_args()
    report_path = Path(args.report_path)
    report = json.loads(report_path.read_text(encoding="utf-8"))
    gate = _validate_report(report, args)

    print("INCIDENT TICKET DRILL EVIDENCE GATE")
    print(json.dumps(gate, indent=2))

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(gate, indent=2), encoding="utf-8")

    return 0 if gate.get("passed") else 1


if __name__ == "__main__":
    raise SystemExit(main())
