name: org-osv

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  osv:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@c5996e0193a3df57d695c1b8a1dec2a4c62e8730 # v2.3.3
    with:
      fail-on-vuln: false
      upload-sarif: false
